# Default values for ksvc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: ""

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

podAnnotations: {}

serviceAccount:
  create: true
  name: ""
  annotations: {}

securityContext: {}

livenessProbe: {}

readinessProbe:
  httpGet:
    path: /
    port: http
  successThreshold: 1

podSecurityContext: {}

containerPorts: []

resources:
  limits:
    cpu: 200m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 32Mi

nodeSelector: {}

tolerations: []

affinity: {}

labels: {}

env: []

secrets: []

files: {}

secretMounts: {}

command: []

args: []

ingress: public # or cluster

scaleToZero: false
