# Default values for ksvc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: ""

image:
  repository: ""
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets:
  - name: harbor-pullsecret

podAnnotations: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

livenessProbe: {}
  # httpGet:
  #   path: /
  #   port: http

readinessProbe:
  httpGet:
    path: /
    port: http
  successThreshold: 1

podSecurityContext: {}
  # fsGroup: 2000

containerPorts: []
  # - name: http
  #   containerPort: 8080
  #   protocol: TCP

# remove defaults when defaults are added to schema
resources:
  limits:
    cpu: 200m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 32Mi

nodeSelector: {}

tolerations: []

affinity: {}

labels: {}

# key value dict of env vars
env: []
  # - name: TARGET
  #   value: deploy

# inject all fields found in secrets by name:
secrets: []
  # - secretName

#  Dictionary of absolute path > content pairs. Useful to override config files.
files: {}
# /etc/nginx/nginx.conf: |
#   ...

# Dictionary of absolute path > secret name. Will mount the contents of the secret in the container at the specified folder path.
secretMounts: {}
# /some/secret/conf: conf-secret-name

# container overrides:
command: []
  # - printenv

args: []
  # - --metric-name=custom_prometheus
  # - --metric-value=40
  # - --port=8080

ingress: public # or cluster

scaleToZero: true
