# Default values for deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


nameOverride: ""

fullnameOverride: ""

replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []

serviceAccount:
  create: false
  annotations: {}
  name: default

podAnnotations: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

livenessProbe: {}
  # httpGet:
  #   path: /
  #   port: http

readinessProbe: {}
  # httpGet:
  #   path: /
  #   port: http

podSecurityContext: {}
  # fsGroup: 2000

servicePorts: []
  # - port: 80
  #   targetPort: http
  #   protocol: TCP
  #   name: http

containerPorts: []
  # - name: http
  #   containerPort: 8080
  #   protocol: TCP

resources: {}
  # limits:
  #   cpu: 200m
  #   memory: 64Mi
  # requests:
  #   cpu: 100m
  #   memory: 32Mi

nodeSelector: {}

tolerations: []

affinity: {}

labels: {}

# key value dict of env vars
env: []
  # - name: TARGET
  #   value: deploy

# inject all fields found in secrets by name:
secrets: []
  # - secretName

#  Dictionary of absolute path > content pairs. Useful to override config files.
files: {}
# /etc/nginx/nginx.conf: |
#   ...

# Dictionary of absolute path > secret name. Will mount the contents of the secret in the container at the specified folder path.
secretMounts: {}
# /some/secret/conf: conf-secret-name

# container overrides:
command: []
  # - printenv

args: []
  # - --metric-name=custom_prometheus
  # - --metric-value=40
  # - --port=8080

autoscaling:
  enabled: false
  # minReplicas: 1
  # maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

serviceMonitor:
  create: false
  endpoints: []
    # - port: metrics
    #   path: /metrics
