# Default values for deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: ""

replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}

podAnnotations: {}

securityContext: {}

livenessProbe: {}

readinessProbe: {}

podSecurityContext: {}

servicePorts:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http

containerPorts: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

labels: {}

env: []

secrets: []

files: {}

secretMounts: {}

# container overrides:
command: []
  # - printenv

args: []
  # - --metric-name=custom_prometheus
  # - --metric-value=40
  # - --port=8080

autoscaling:
  enabled: false
  # minReplicas: 1
  # maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

serviceMonitor:
  create: false
  endpoints: []
    # - port: metrics
    #   path: /metrics
