# Default values for ksvc.

fullnameOverride: ""

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

podAnnotations: {}

serviceAccount:
  create: false
  annotations: {}
  imagePullSecrets: []

securityContext: {}

livenessProbe: {}

readinessProbe:
  httpGet:
    path: /
    port: http
  successThreshold: 1

containerSecurityContext: {}

containerPorts: []

resources:
  limits:
    cpu: 200m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 32Mi

nodeSelector: {}

tolerations: []

affinity: {}

labels: {}

env: []

secrets: []

files: {}

secretMounts: {}

command: []

args: []

ingress: public

scaleToZero: false
