# Default values for deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kubeVersion: ""

fullnameOverride: ""

replicaCount: 2

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

serviceAccount:
  annotations: {}
  imagePullSecrets: []

podAnnotations: {}

securityContext: {}

livenessProbe: {}

readinessProbe: {}

containerSecurityContext: {}

servicePorts:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http

containerPorts: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

labels: {}

env: []

secrets: []

files: {}

secretMounts: {}

command: []

args: []

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPU: 80
  targetMemory: 80

serviceMonitor:
  create: false
  endpoints: []
