{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "deployment.fullnameOverride" . }}
  labels: {{- include "deployment.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.Annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
imagePullSecrets:

{{- with .Values.imagePullSecrets }}
{{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
