{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets: {{- toYaml . | nindent 2 }}
  {{- end }}
metadata:
  name: {{ include "deployment.fullnameOverride" . }}
  labels: {{- include "deployment.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.Annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
